
INSERT INTO projects (title,category,funding_goal,start_date,end_date) VALUES ("tincidunt adipiscing.","Nunc Laoreet Lectus Foundation",9500,1,6);
INSERT INTO projects (title,category,funding_goal,start_date,end_date) VALUES ("erat vitae","Ornare Lectus Ante Limited",95708,2,3);
INSERT INTO projects (title,category,funding_goal,start_date,end_date) VALUES ("Nullam nisl.","Nulla Corp.",45289,2,12);
INSERT INTO projects (title,category,funding_goal,start_date,end_date) VALUES ("feugiat tellus","Nullam Velit Dui LLP",60560,10,10);
INSERT INTO projects (title,category,funding_goal,start_date,end_date) VALUES ("lacus. Cras","Interdum Enim Non Limited",14477,9,1);
INSERT INTO projects (title,category,funding_goal,start_date,end_date) VALUES ("id sapien.","Donec Institute",44689,11,2);
INSERT INTO projects (title,category,funding_goal,start_date,end_date) VALUES ("fringilla euismod","Tempus Lorem Fringilla LLP",9750,4,2);
INSERT INTO projects (title,category,funding_goal,start_date,end_date) VALUES ("laoreet posuere,","Neque Morbi Quis Associates",70868,6,3);
INSERT INTO projects (title,category,funding_goal,start_date,end_date) VALUES ("magna a","Nunc Quisque Consulting",34129,7,9);
INSERT INTO projects (title,category,funding_goal,start_date,end_date) VALUES ("nonummy ut,","Ligula Tortor Dictum Limited",99671,4,8);

INSERT INTO users (name,age) VALUES ("Nola Murphy",42);
INSERT INTO users (name,age) VALUES ("Cade Lloyd",30);
INSERT INTO users (name,age) VALUES ("Salvador Riley",33);
INSERT INTO users (name,age) VALUES ("Len David",44);
INSERT INTO users (name,age) VALUES ("Elton Ferguson",37);
INSERT INTO users (name,age) VALUES ("Ryder Boone",20);
INSERT INTO users (name,age) VALUES ("Breanna Harding",37);
INSERT INTO users (name,age) VALUES ("Constance Rutledge",49);
INSERT INTO users (name,age) VALUES ("Nolan Forbes",34);
INSERT INTO users (name,age) VALUES ("Merritt Dawson",21);
INSERT INTO users (name,age) VALUES ("Ivory Conway",39);
INSERT INTO users (name,age) VALUES ("Joshua Cummings",31);
INSERT INTO users (name,age) VALUES ("Anastasia Merritt",27);
INSERT INTO users (name,age) VALUES ("Paloma Malone",32);
INSERT INTO users (name,age) VALUES ("Prescott Todd",44);
INSERT INTO users (name,age) VALUES ("Carl Paul",18);
INSERT INTO users (name,age) VALUES ("Michael Crane",26);
INSERT INTO users (name,age) VALUES ("Myles Terrell",34);
INSERT INTO users (name,age) VALUES ("Courtney Harvey",18);
INSERT INTO users (name,age) VALUES ("Charlotte Berger",50);

INSERT INTO pledges (amount,user_id,project_id) VALUES (3223,14,5);
INSERT INTO pledges (amount,user_id,project_id) VALUES (4275,14,5);
INSERT INTO pledges (amount,user_id,project_id) VALUES (1483,1,9);
INSERT INTO pledges (amount,user_id,project_id) VALUES (1471,3,5);
INSERT INTO pledges (amount,user_id,project_id) VALUES (2400,15,4);
INSERT INTO pledges (amount,user_id,project_id) VALUES (3003,8,5);
INSERT INTO pledges (amount,user_id,project_id) VALUES (3426,16,5);
INSERT INTO pledges (amount,user_id,project_id) VALUES (1589,4,6);
INSERT INTO pledges (amount,user_id,project_id) VALUES (1247,16,4);
INSERT INTO pledges (amount,user_id,project_id) VALUES (960,6,1);
INSERT INTO pledges (amount,user_id,project_id) VALUES (2270,20,9);
INSERT INTO pledges (amount,user_id,project_id) VALUES (1375,9,5);
INSERT INTO pledges (amount,user_id,project_id) VALUES (2278,14,2);
INSERT INTO pledges (amount,user_id,project_id) VALUES (3929,2,1);
INSERT INTO pledges (amount,user_id,project_id) VALUES (3001,16,3);
INSERT INTO pledges (amount,user_id,project_id) VALUES (1713,10,3);
INSERT INTO pledges (amount,user_id,project_id) VALUES (2418,15,2);
INSERT INTO pledges (amount,user_id,project_id) VALUES (1003,10,2);
INSERT INTO pledges (amount,user_id,project_id) VALUES (3012,3,9);
INSERT INTO pledges (amount,user_id,project_id) VALUES (4111,10,1);
INSERT INTO pledges (amount,user_id,project_id) VALUES (1090,19,2);
INSERT INTO pledges (amount,user_id,project_id) VALUES (3939,8,8);
INSERT INTO pledges (amount,user_id,project_id) VALUES (2467,13,3);
INSERT INTO pledges (amount,user_id,project_id) VALUES (3667,4,4);
INSERT INTO pledges (amount,user_id,project_id) VALUES (2898,1,4);
INSERT INTO pledges (amount,user_id,project_id) VALUES (3648,17,6);
INSERT INTO pledges (amount,user_id,project_id) VALUES (2648,17,4);
INSERT INTO pledges (amount,user_id,project_id) VALUES (2950,11,4);
INSERT INTO pledges (amount,user_id,project_id) VALUES (4893,1,8);
INSERT INTO pledges (amount,user_id,project_id) VALUES (1517,7,9);
